#!/usr/bin/env bash

add-apt-repository ppa:ondrej/php
apt-get -y update
apt-get -y install python-software-properties
apt-get -y install apache2

## installing mysql
debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'
debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'
apt-get -y install mysql-server

apt-get -y install php5.6 php5.6-mbstring php5.6-mcrypt php5.6-mysql php5.6-xml php5.6-gd php5.6-ldap php5.6-curl php5.6-cli php5.6-soap

cp /home/vagrant/var/php.ini /etc/php/5.6/apache2/php.ini

cd /tmp
wget http://pilotfiber.dl.sourceforge.net/project/processmaker/ProcessMaker/3.1.3/processmaker-3.1.3-community.tar.gz

tar -C /opt -xzvf processmaker-3.1.3-community.tar.gz

cd /opt/processmaker
sudo chmod -R 770 shared workflow/public_html gulliver/js gulliver/thirdparty/html2ps_pdf/cache
cd workflow/engine/
sudo chmod -R 770 config content/languages plugins xmlform js/labels
sudo chown -R www-data:www-data /opt/processmaker

cp /home/vagrant/var/pmos.conf /etc/apache2/sites-available/pmos.conf

ln -s /etc/apache2/mods-available/expires.load /etc/apache2/mods-enabled/

a2ensite pmos.conf

service apache2 reload

a2enmod ldap
a2enmod authnz_ldap
a2enmod deflate
a2enmod expires
a2enmod rewrite 
a2enmod ssl
a2enmod vhost_alias
a2enmod filter

a2dissite 000-default.conf
service apache2 restart